#############################################################################
# Makefile for building: video_to_picture_widget.app/Contents/MacOS/video_to_picture_widget
# Generated by qmake (3.1) (Qt 6.5.1)
# Project:  ../video_to_picture_widget/video_to_picture_widget.pro
# Template: app
# Command: /Users/twinklecat/Qt/6.5.1/macos/bin/qmake -o Makefile ../video_to_picture_widget/video_to_picture_widget.pro -spec macx-clang CONFIG+=qtquickcompiler
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk -mmacosx-version-min=11.0 -Wall -Wextra $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -O2 -std=gnu++1z $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk -mmacosx-version-min=11.0 -Wall -Wextra $(DEFINES)
INCPATH       = -I../video_to_picture_widget -I. -I/opt/homebrew/Cellar/opencv/4.7.0_2/include/opencv4 -I../../../Qt/6.5.1/macos/lib/QtWidgets.framework/Headers -I../../../Qt/6.5.1/macos/lib/QtGui.framework/Headers -I../../../Qt/6.5.1/macos/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk/System/Library/Frameworks/AGL.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk/System/Library/Frameworks/AGL.framework/Headers -I../../../Qt/6.5.1/macos/mkspecs/macx-clang -F/Users/twinklecat/Qt/6.5.1/macos/lib
QMAKE         = /Users/twinklecat/Qt/6.5.1/macos/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /Users/twinklecat/Qt/6.5.1/macos/bin/qmake -install qinstall
QINSTALL_PROGRAM = /Users/twinklecat/Qt/6.5.1/macos/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = video_to_picture_widget1.0.0
DISTDIR = /Users/twinklecat/Downloads/video_to_picture_widget/build-video_to_picture_widget-Qt_6_5_1_for_macOS-Release/.tmp/video_to_picture_widget1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -stdlib=libc++ -headerpad_max_install_names $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk -mmacosx-version-min=11.0 -Wl,-rpath,@executable_path/../Frameworks -Wl,-rpath,/Users/twinklecat/Qt/6.5.1/macos/lib
LIBS          = $(SUBLIBS) -F/Users/twinklecat/Qt/6.5.1/macos/lib /opt/homebrew/Cellar/opencv/4.7.0_2/lib/libopencv_core.dylib /opt/homebrew/Cellar/opencv/4.7.0_2/lib/libopencv_imgcodecs.dylib /opt/homebrew/Cellar/opencv/4.7.0_2/lib/libopencv_videoio.dylib -framework QtWidgets -framework QtGui -framework AppKit -framework ImageIO -framework Metal -framework QtCore -framework IOKit -framework DiskArbitration -framework AGL -framework OpenGL   
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = ../video_to_picture_widget/main.cpp \
		../video_to_picture_widget/mainwindow.cpp moc_mainwindow.cpp
OBJECTS       = main.o \
		mainwindow.o \
		moc_mainwindow.o
DIST          = ../../../Qt/6.5.1/macos/mkspecs/features/spec_pre.prf \
		../../../Qt/6.5.1/macos/mkspecs/features/device_config.prf \
		../../../Qt/6.5.1/macos/mkspecs/common/unix.conf \
		../../../Qt/6.5.1/macos/mkspecs/common/mac.conf \
		../../../Qt/6.5.1/macos/mkspecs/common/macx.conf \
		../../../Qt/6.5.1/macos/mkspecs/common/sanitize.conf \
		../../../Qt/6.5.1/macos/mkspecs/common/gcc-base.conf \
		../../../Qt/6.5.1/macos/mkspecs/common/gcc-base-mac.conf \
		../../../Qt/6.5.1/macos/mkspecs/common/clang.conf \
		../../../Qt/6.5.1/macos/mkspecs/common/clang-mac.conf \
		../../../Qt/6.5.1/macos/mkspecs/qconfig.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_ext_freetype.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_ext_libjpeg.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_ext_libpng.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_3danimation.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_3dcore.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_3dextras.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_3dinput.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_3dquick.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_3drender.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_bodymovin_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_charts.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_charts_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_chartsqml.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_chartsqml_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_core.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_core5compat.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_core5compat_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_core_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_datavisualization.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_datavisualizationqml.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_datavisualizationqml_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_dbus.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_designer.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_example_icons_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_freetype_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_grpc.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_grpc_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_gui.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_harfbuzz_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_help.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_help_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_httpserver.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_httpserver_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_insighttracker.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_insighttracker_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_insighttrackerqml.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_insighttrackerqml_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_jpeg_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_jsonrpc_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_labsanimation.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_labsanimation_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_labssettings.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_labssettings_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_labssharedimage.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_languageserver_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_linguist.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_linguist_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_location.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_location_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_multimediaquick_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_network.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_network_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_networkauth.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_nfc.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_opengl.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_openglwidgets.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_pdf.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_pdf_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_pdfquick.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_pdfquick_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_pdfwidgets.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_pdfwidgets_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_png_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_positioning.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_positioningquick.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_positioningquick_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_protobuf.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_protobuf_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_qml.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_qmlcore.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_qmlcore_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_qmldom_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_qmlintegration.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_qmlintegration_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_qmlmodels.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_qmltyperegistrar_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_qmlxmllistmodel.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quick.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quick3d.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quick3d_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quick3dassetutils.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quick3dassetutils_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quick3deffects.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quick3deffects_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quick3dglslparser_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quick3dhelpers.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quick3dhelpers_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quick3dhelpersimpl.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quick3dhelpersimpl_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quick3diblbaker.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quick3diblbaker_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quick3dparticleeffects.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quick3dparticleeffects_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quick3dparticles.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quick3dparticles_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quick3dphysics.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quick3dphysics_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quick3dphysicshelpers.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quick3dphysicshelpers_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quick3dspatialaudio_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quick3dutils.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quickdialogs2.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quickdialogs2_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quickdialogs2utils.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quickeffects_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quicklayouts.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quicktimeline.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quicktimeline_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_remoteobjectsqml.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_remoteobjectsqml_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_repparser.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_repparser_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_scxml.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_scxml_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_scxmlqml.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_scxmlqml_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_sensors.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_sensorsquick.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_sensorsquick_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_serialbus.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_serialport.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_shadertools.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_shadertools_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_spatialaudio.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_spatialaudio_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_sql.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_statemachine.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_statemachine_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_statemachineqml.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_statemachineqml_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_svg.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_svgwidgets.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_svgwidgets_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_testlib.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_texttospeech.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_tools_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_uitools.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_webchannel.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_webenginequick.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_webenginequick_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_webenginequickdelegatesqml.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_webenginequickdelegatesqml_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_websockets.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_webview.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_webview_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_webviewquick.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_webviewquick_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_widgets.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_xml.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_plugin_qdarwinbluetoothpermission.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_plugin_qdarwincalendarpermission.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_plugin_qdarwincamerapermission.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_plugin_qdarwincontactspermission.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_plugin_qdarwinlocationpermission.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_plugin_qdarwinmicrophonepermission.pri \
		../../../Qt/6.5.1/macos/mkspecs/features/qt_functions.prf \
		../../../Qt/6.5.1/macos/mkspecs/features/qt_config.prf \
		../../../Qt/6.5.1/macos/mkspecs/macx-clang/qmake.conf \
		../../../Qt/6.5.1/macos/mkspecs/features/spec_post.prf \
		../../../Qt/6.5.1/macos/mkspecs/features/exclusive_builds.prf \
		../../../Qt/6.5.1/macos/mkspecs/features/mac/sdk.prf \
		../../../Qt/6.5.1/macos/mkspecs/features/toolchain.prf \
		../../../Qt/6.5.1/macos/mkspecs/features/mac/toolchain.prf \
		../../../Qt/6.5.1/macos/mkspecs/features/default_pre.prf \
		../../../Qt/6.5.1/macos/mkspecs/features/mac/default_pre.prf \
		../../../Qt/6.5.1/macos/mkspecs/features/resolve_config.prf \
		../../../Qt/6.5.1/macos/mkspecs/features/default_post.prf \
		../../../Qt/6.5.1/macos/mkspecs/features/mac/default_post.prf \
		../../../Qt/6.5.1/macos/mkspecs/features/mac/objective_c.prf \
		../../../Qt/6.5.1/macos/mkspecs/features/qtquickcompiler.prf \
		../../../Qt/6.5.1/macos/mkspecs/features/mac/mac.prf \
		../../../Qt/6.5.1/macos/mkspecs/features/warn_on.prf \
		../../../Qt/6.5.1/macos/mkspecs/features/permissions.prf \
		../../../Qt/6.5.1/macos/mkspecs/features/qt.prf \
		../../../Qt/6.5.1/macos/mkspecs/features/resources_functions.prf \
		../../../Qt/6.5.1/macos/mkspecs/features/resources.prf \
		../../../Qt/6.5.1/macos/mkspecs/features/moc.prf \
		../../../Qt/6.5.1/macos/mkspecs/features/unix/opengl.prf \
		../../../Qt/6.5.1/macos/mkspecs/features/uic.prf \
		../../../Qt/6.5.1/macos/mkspecs/features/unix/thread.prf \
		../../../Qt/6.5.1/macos/mkspecs/features/qmake_use.prf \
		../../../Qt/6.5.1/macos/mkspecs/features/file_copies.prf \
		../../../Qt/6.5.1/macos/mkspecs/features/mac/rez.prf \
		../../../Qt/6.5.1/macos/mkspecs/features/mac/asset_catalogs.prf \
		../../../Qt/6.5.1/macos/mkspecs/features/testcase_targets.prf \
		../../../Qt/6.5.1/macos/mkspecs/features/exceptions.prf \
		../../../Qt/6.5.1/macos/mkspecs/features/yacc.prf \
		../../../Qt/6.5.1/macos/mkspecs/features/lex.prf \
		../video_to_picture_widget/video_to_picture_widget.pro ../video_to_picture_widget/mainwindow.h ../video_to_picture_widget/main.cpp \
		../video_to_picture_widget/mainwindow.cpp
QMAKE_TARGET  = video_to_picture_widget
DESTDIR       = 
TARGET        = video_to_picture_widget.app/Contents/MacOS/video_to_picture_widget

####### Custom Variables
EXPORT_QMAKE_MAC_SDK = macosx
EXPORT_QMAKE_MAC_SDK_VERSION = 13.3
EXPORT_QMAKE_XCODE_DEVELOPER_PATH = /Applications/Xcode.app/Contents/Developer
EXPORT__QMAKE_STASH_ = 
EXPORT_VALID_ARCHS = x86_64 arm64
EXPORT_DEFAULT_ARCHS = arm64
EXPORT_ARCHS = $(filter $(EXPORT_VALID_ARCHS), $(if $(ARCHS), $(ARCHS), $(if $(EXPORT_DEFAULT_ARCHS), $(EXPORT_DEFAULT_ARCHS), $(EXPORT_VALID_ARCHS))))
EXPORT_ARCH_ARGS = $(foreach arch, $(if $(EXPORT_ARCHS), $(EXPORT_ARCHS), $(EXPORT_VALID_ARCHS)), -arch $(arch))
EXPORT__PRO_FILE_ = /Users/twinklecat/Downloads/video_to_picture_widget/video_to_picture_widget/video_to_picture_widget.pro


include /Users/twinklecat/Qt/6.5.1/macos/mkspecs/features/mac/sdk.mk
first: all
####### Build rules

video_to_picture_widget.app/Contents/MacOS/video_to_picture_widget: ui_mainwindow.h $(OBJECTS)  
	@test -d video_to_picture_widget.app/Contents/MacOS/ || mkdir -p video_to_picture_widget.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET)  $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: ../video_to_picture_widget/video_to_picture_widget.pro ../../../Qt/6.5.1/macos/mkspecs/macx-clang/qmake.conf ../../../Qt/6.5.1/macos/mkspecs/features/spec_pre.prf \
		../../../Qt/6.5.1/macos/mkspecs/features/device_config.prf \
		../../../Qt/6.5.1/macos/mkspecs/common/unix.conf \
		../../../Qt/6.5.1/macos/mkspecs/common/mac.conf \
		../../../Qt/6.5.1/macos/mkspecs/common/macx.conf \
		../../../Qt/6.5.1/macos/mkspecs/common/sanitize.conf \
		../../../Qt/6.5.1/macos/mkspecs/common/gcc-base.conf \
		../../../Qt/6.5.1/macos/mkspecs/common/gcc-base-mac.conf \
		../../../Qt/6.5.1/macos/mkspecs/common/clang.conf \
		../../../Qt/6.5.1/macos/mkspecs/common/clang-mac.conf \
		../../../Qt/6.5.1/macos/mkspecs/qconfig.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_ext_freetype.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_ext_libjpeg.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_ext_libpng.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_3danimation.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_3dcore.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_3dextras.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_3dinput.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_3dquick.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_3drender.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_bodymovin_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_charts.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_charts_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_chartsqml.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_chartsqml_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_core.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_core5compat.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_core5compat_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_core_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_datavisualization.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_datavisualizationqml.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_datavisualizationqml_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_dbus.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_designer.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_example_icons_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_freetype_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_grpc.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_grpc_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_gui.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_harfbuzz_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_help.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_help_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_httpserver.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_httpserver_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_insighttracker.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_insighttracker_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_insighttrackerqml.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_insighttrackerqml_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_jpeg_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_jsonrpc_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_labsanimation.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_labsanimation_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_labssettings.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_labssettings_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_labssharedimage.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_languageserver_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_linguist.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_linguist_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_location.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_location_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_multimediaquick_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_network.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_network_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_networkauth.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_nfc.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_opengl.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_openglwidgets.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_pdf.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_pdf_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_pdfquick.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_pdfquick_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_pdfwidgets.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_pdfwidgets_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_png_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_positioning.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_positioningquick.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_positioningquick_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_protobuf.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_protobuf_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_qml.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_qmlcore.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_qmlcore_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_qmldom_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_qmlintegration.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_qmlintegration_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_qmlmodels.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_qmltyperegistrar_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_qmlxmllistmodel.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quick.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quick3d.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quick3d_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quick3dassetutils.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quick3dassetutils_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quick3deffects.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quick3deffects_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quick3dglslparser_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quick3dhelpers.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quick3dhelpers_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quick3dhelpersimpl.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quick3dhelpersimpl_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quick3diblbaker.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quick3diblbaker_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quick3dparticleeffects.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quick3dparticleeffects_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quick3dparticles.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quick3dparticles_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quick3dphysics.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quick3dphysics_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quick3dphysicshelpers.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quick3dphysicshelpers_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quick3dspatialaudio_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quick3dutils.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quickdialogs2.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quickdialogs2_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quickdialogs2utils.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quickeffects_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quicklayouts.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quicktimeline.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quicktimeline_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_remoteobjectsqml.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_remoteobjectsqml_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_repparser.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_repparser_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_scxml.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_scxml_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_scxmlqml.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_scxmlqml_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_sensors.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_sensorsquick.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_sensorsquick_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_serialbus.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_serialport.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_shadertools.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_shadertools_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_spatialaudio.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_spatialaudio_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_sql.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_statemachine.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_statemachine_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_statemachineqml.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_statemachineqml_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_svg.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_svgwidgets.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_svgwidgets_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_testlib.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_texttospeech.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_tools_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_uitools.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_webchannel.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_webenginequick.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_webenginequick_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_webenginequickdelegatesqml.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_webenginequickdelegatesqml_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_websockets.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_webview.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_webview_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_webviewquick.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_webviewquick_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_widgets.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_xml.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_plugin_qdarwinbluetoothpermission.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_plugin_qdarwincalendarpermission.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_plugin_qdarwincamerapermission.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_plugin_qdarwincontactspermission.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_plugin_qdarwinlocationpermission.pri \
		../../../Qt/6.5.1/macos/mkspecs/modules/qt_plugin_qdarwinmicrophonepermission.pri \
		../../../Qt/6.5.1/macos/mkspecs/features/qt_functions.prf \
		../../../Qt/6.5.1/macos/mkspecs/features/qt_config.prf \
		../../../Qt/6.5.1/macos/mkspecs/macx-clang/qmake.conf \
		../../../Qt/6.5.1/macos/mkspecs/features/spec_post.prf \
		../../../Qt/6.5.1/macos/mkspecs/features/exclusive_builds.prf \
		../../../Qt/6.5.1/macos/mkspecs/features/mac/sdk.prf \
		../../../Qt/6.5.1/macos/mkspecs/features/toolchain.prf \
		../../../Qt/6.5.1/macos/mkspecs/features/mac/toolchain.prf \
		../../../Qt/6.5.1/macos/mkspecs/features/default_pre.prf \
		../../../Qt/6.5.1/macos/mkspecs/features/mac/default_pre.prf \
		../../../Qt/6.5.1/macos/mkspecs/features/resolve_config.prf \
		../../../Qt/6.5.1/macos/mkspecs/features/default_post.prf \
		../../../Qt/6.5.1/macos/mkspecs/features/mac/default_post.prf \
		../../../Qt/6.5.1/macos/mkspecs/features/mac/objective_c.prf \
		../../../Qt/6.5.1/macos/mkspecs/features/qtquickcompiler.prf \
		../../../Qt/6.5.1/macos/mkspecs/features/mac/mac.prf \
		../../../Qt/6.5.1/macos/mkspecs/features/warn_on.prf \
		../../../Qt/6.5.1/macos/mkspecs/features/permissions.prf \
		../../../Qt/6.5.1/macos/mkspecs/features/qt.prf \
		../../../Qt/6.5.1/macos/mkspecs/features/resources_functions.prf \
		../../../Qt/6.5.1/macos/mkspecs/features/resources.prf \
		../../../Qt/6.5.1/macos/mkspecs/features/moc.prf \
		../../../Qt/6.5.1/macos/mkspecs/features/unix/opengl.prf \
		../../../Qt/6.5.1/macos/mkspecs/features/uic.prf \
		../../../Qt/6.5.1/macos/mkspecs/features/unix/thread.prf \
		../../../Qt/6.5.1/macos/mkspecs/features/qmake_use.prf \
		../../../Qt/6.5.1/macos/mkspecs/features/file_copies.prf \
		../../../Qt/6.5.1/macos/mkspecs/features/mac/rez.prf \
		../../../Qt/6.5.1/macos/mkspecs/features/mac/asset_catalogs.prf \
		../../../Qt/6.5.1/macos/mkspecs/features/testcase_targets.prf \
		../../../Qt/6.5.1/macos/mkspecs/features/exceptions.prf \
		../../../Qt/6.5.1/macos/mkspecs/features/yacc.prf \
		../../../Qt/6.5.1/macos/mkspecs/features/lex.prf \
		../video_to_picture_widget/video_to_picture_widget.pro \
		../../../Qt/6.5.1/macos/lib/QtWidgets.framework/Resources/QtWidgets.prl \
		../../../Qt/6.5.1/macos/lib/QtGui.framework/Resources/QtGui.prl \
		../../../Qt/6.5.1/macos/lib/QtCore.framework/Resources/QtCore.prl
	$(QMAKE) -o Makefile ../video_to_picture_widget/video_to_picture_widget.pro -spec macx-clang CONFIG+=qtquickcompiler
../../../Qt/6.5.1/macos/mkspecs/features/spec_pre.prf:
../../../Qt/6.5.1/macos/mkspecs/features/device_config.prf:
../../../Qt/6.5.1/macos/mkspecs/common/unix.conf:
../../../Qt/6.5.1/macos/mkspecs/common/mac.conf:
../../../Qt/6.5.1/macos/mkspecs/common/macx.conf:
../../../Qt/6.5.1/macos/mkspecs/common/sanitize.conf:
../../../Qt/6.5.1/macos/mkspecs/common/gcc-base.conf:
../../../Qt/6.5.1/macos/mkspecs/common/gcc-base-mac.conf:
../../../Qt/6.5.1/macos/mkspecs/common/clang.conf:
../../../Qt/6.5.1/macos/mkspecs/common/clang-mac.conf:
../../../Qt/6.5.1/macos/mkspecs/qconfig.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_ext_freetype.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_ext_libjpeg.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_ext_libpng.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_3danimation.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_3danimation_private.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_3dcore.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_3dcore_private.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_3dextras.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_3dextras_private.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_3dinput.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_3dinput_private.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_3dlogic.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_3dquick.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_3dquick_private.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_3dquickanimation.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_3dquickextras.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_3dquickinput.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_3dquickrender.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_3dquickscene2d.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_3drender.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_3drender_private.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_bluetooth.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_bodymovin_private.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_charts.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_charts_private.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_chartsqml.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_chartsqml_private.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_concurrent.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_core.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_core5compat.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_core5compat_private.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_core_private.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_datavisualization.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_datavisualization_private.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_datavisualizationqml.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_datavisualizationqml_private.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_dbus.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_dbus_private.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_designer.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_designer_private.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_example_icons_private.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_fb_support_private.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_freetype_private.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_grpc.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_grpc_private.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_gui.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_gui_private.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_harfbuzz_private.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_help.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_help_private.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_httpserver.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_httpserver_private.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_insighttracker.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_insighttracker_private.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_insighttrackerqml.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_insighttrackerqml_private.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_jpeg_private.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_jsonrpc_private.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_labsanimation.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_labsanimation_private.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_labsfolderlistmodel.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_labsqmlmodels.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_labsqmlmodels_private.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_labssettings.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_labssettings_private.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_labssharedimage.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_labssharedimage_private.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_labswavefrontmesh.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_languageserver_private.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_linguist.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_linguist_private.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_location.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_location_private.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_multimedia.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_multimediaquick_private.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_network.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_network_private.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_networkauth.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_networkauth_private.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_nfc.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_nfc_private.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_opengl.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_opengl_private.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_openglwidgets.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_openglwidgets_private.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_pdf.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_pdf_private.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_pdfquick.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_pdfquick_private.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_pdfwidgets.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_pdfwidgets_private.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_png_private.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_positioning.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_positioning_private.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_positioningquick.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_positioningquick_private.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_printsupport.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_protobuf.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_protobuf_private.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_qml.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_qml_private.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_qmlcompiler_private.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_qmlcore.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_qmlcore_private.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_qmldom_private.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_qmlintegration.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_qmlintegration_private.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_qmllocalstorage.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_qmllocalstorage_private.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_qmlmodels.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_qmlmodels_private.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_qmltest.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_qmltyperegistrar_private.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_qmlworkerscript.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_qmlxmllistmodel.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quick.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quick3d.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quick3d_private.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quick3dassetimport.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quick3dassetimport_private.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quick3dassetutils.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quick3dassetutils_private.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quick3deffects.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quick3deffects_private.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quick3dglslparser_private.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quick3dhelpers.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quick3dhelpers_private.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quick3dhelpersimpl.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quick3dhelpersimpl_private.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quick3diblbaker.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quick3diblbaker_private.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quick3dparticleeffects.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quick3dparticleeffects_private.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quick3dparticles.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quick3dparticles_private.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quick3dphysics.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quick3dphysics_private.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quick3dphysicshelpers.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quick3dphysicshelpers_private.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quick3druntimerender.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quick3druntimerender_private.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quick3dspatialaudio_private.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quick3dutils.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quick3dutils_private.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quick_private.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quickcontrols2impl.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quickdialogs2.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quickdialogs2_private.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quickdialogs2utils.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quickeffects_private.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quicklayouts.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quicklayouts_private.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quickshapes_private.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quicktemplates2.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quicktimeline.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quicktimeline_private.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_remoteobjects.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_remoteobjects_private.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_remoteobjectsqml.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_remoteobjectsqml_private.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_repparser.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_repparser_private.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_scxml.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_scxml_private.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_scxmlqml.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_scxmlqml_private.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_sensors.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_sensors_private.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_sensorsquick.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_sensorsquick_private.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_serialbus.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_serialbus_private.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_serialport.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_serialport_private.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_shadertools.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_shadertools_private.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_spatialaudio.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_spatialaudio_private.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_sql.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_sql_private.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_statemachine.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_statemachine_private.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_statemachineqml.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_statemachineqml_private.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_svg.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_svg_private.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_svgwidgets.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_svgwidgets_private.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_testlib.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_testlib_private.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_texttospeech.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_texttospeech_private.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_tools_private.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_uiplugin.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_uitools.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_uitools_private.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_virtualkeyboard.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_virtualkeyboard_private.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_webchannel.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_webchannel_private.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_webenginecore.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_webenginequick.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_webenginequick_private.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_webenginequickdelegatesqml.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_webenginequickdelegatesqml_private.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_websockets.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_websockets_private.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_webview.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_webview_private.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_webviewquick.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_webviewquick_private.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_widgets.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_widgets_private.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_xml.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_lib_xml_private.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_plugin_qdarwinbluetoothpermission.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_plugin_qdarwincalendarpermission.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_plugin_qdarwincamerapermission.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_plugin_qdarwincontactspermission.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_plugin_qdarwinlocationpermission.pri:
../../../Qt/6.5.1/macos/mkspecs/modules/qt_plugin_qdarwinmicrophonepermission.pri:
../../../Qt/6.5.1/macos/mkspecs/features/qt_functions.prf:
../../../Qt/6.5.1/macos/mkspecs/features/qt_config.prf:
../../../Qt/6.5.1/macos/mkspecs/macx-clang/qmake.conf:
../../../Qt/6.5.1/macos/mkspecs/features/spec_post.prf:
../../../Qt/6.5.1/macos/mkspecs/features/exclusive_builds.prf:
../../../Qt/6.5.1/macos/mkspecs/features/mac/sdk.prf:
../../../Qt/6.5.1/macos/mkspecs/features/toolchain.prf:
../../../Qt/6.5.1/macos/mkspecs/features/mac/toolchain.prf:
../../../Qt/6.5.1/macos/mkspecs/features/default_pre.prf:
../../../Qt/6.5.1/macos/mkspecs/features/mac/default_pre.prf:
../../../Qt/6.5.1/macos/mkspecs/features/resolve_config.prf:
../../../Qt/6.5.1/macos/mkspecs/features/default_post.prf:
../../../Qt/6.5.1/macos/mkspecs/features/mac/default_post.prf:
../../../Qt/6.5.1/macos/mkspecs/features/mac/objective_c.prf:
../../../Qt/6.5.1/macos/mkspecs/features/qtquickcompiler.prf:
../../../Qt/6.5.1/macos/mkspecs/features/mac/mac.prf:
../../../Qt/6.5.1/macos/mkspecs/features/warn_on.prf:
../../../Qt/6.5.1/macos/mkspecs/features/permissions.prf:
../../../Qt/6.5.1/macos/mkspecs/features/qt.prf:
../../../Qt/6.5.1/macos/mkspecs/features/resources_functions.prf:
../../../Qt/6.5.1/macos/mkspecs/features/resources.prf:
../../../Qt/6.5.1/macos/mkspecs/features/moc.prf:
../../../Qt/6.5.1/macos/mkspecs/features/unix/opengl.prf:
../../../Qt/6.5.1/macos/mkspecs/features/uic.prf:
../../../Qt/6.5.1/macos/mkspecs/features/unix/thread.prf:
../../../Qt/6.5.1/macos/mkspecs/features/qmake_use.prf:
../../../Qt/6.5.1/macos/mkspecs/features/file_copies.prf:
../../../Qt/6.5.1/macos/mkspecs/features/mac/rez.prf:
../../../Qt/6.5.1/macos/mkspecs/features/mac/asset_catalogs.prf:
../../../Qt/6.5.1/macos/mkspecs/features/testcase_targets.prf:
../../../Qt/6.5.1/macos/mkspecs/features/exceptions.prf:
../../../Qt/6.5.1/macos/mkspecs/features/yacc.prf:
../../../Qt/6.5.1/macos/mkspecs/features/lex.prf:
../video_to_picture_widget/video_to_picture_widget.pro:
../../../Qt/6.5.1/macos/lib/QtWidgets.framework/Resources/QtWidgets.prl:
../../../Qt/6.5.1/macos/lib/QtGui.framework/Resources/QtGui.prl:
../../../Qt/6.5.1/macos/lib/QtCore.framework/Resources/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile ../video_to_picture_widget/video_to_picture_widget.pro -spec macx-clang CONFIG+=qtquickcompiler

qmake_all: FORCE

video_to_picture_widget.app/Contents/PkgInfo: 
	@test -d video_to_picture_widget.app/Contents || mkdir -p video_to_picture_widget.app/Contents
	@$(DEL_FILE) video_to_picture_widget.app/Contents/PkgInfo
	@echo "APPL????" > video_to_picture_widget.app/Contents/PkgInfo
video_to_picture_widget.app/Contents/Info.plist: 
	@test -d video_to_picture_widget.app/Contents || mkdir -p video_to_picture_widget.app/Contents
	@$(DEL_FILE) video_to_picture_widget.app/Contents/Info.plist
	@plutil -convert xml1 -o - ../../../Qt/6.5.1/macos/mkspecs/macx-clang/Info.plist.app | sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,\$${QMAKE_SHORT_VERSION},1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,\$${QMAKE_FULL_VERSION},1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" -e "s,@BUNDLEIDENTIFIER@,iosTest.video-to-picture-widget,g" -e "s,\$${PRODUCT_BUNDLE_IDENTIFIER},iosTest.video-to-picture-widget,g" -e "s,\$${MACOSX_DEPLOYMENT_TARGET},11.0,g" -e "s,\$${IPHONEOS_DEPLOYMENT_TARGET},,g" -e "s,\$${TVOS_DEPLOYMENT_TARGET},,g" -e "s,\$${WATCHOS_DEPLOYMENT_TARGET},,g" -e "s,\$${IOS_LAUNCH_SCREEN},LaunchScreen,g" -e "s,@ICON@,,g" -e "s,\$${ASSETCATALOG_COMPILER_APPICON_NAME},,g" -e "s,@EXECUTABLE@,video_to_picture_widget,g" -e "s,@LIBRARY@,video_to_picture_widget,g" -e "s,\$${EXECUTABLE_NAME},video_to_picture_widget,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" >video_to_picture_widget.app/Contents/Info.plist

all: Makefile \
		video_to_picture_widget.app/Contents/PkgInfo \
		video_to_picture_widget.app/Contents/Info.plist video_to_picture_widget.app/Contents/MacOS/video_to_picture_widget

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents ../video_to_picture_widget/mainwindow.h $(DISTDIR)/
	$(COPY_FILE) --parents ../video_to_picture_widget/main.cpp ../video_to_picture_widget/mainwindow.cpp $(DISTDIR)/
	$(COPY_FILE) --parents ../video_to_picture_widget/mainwindow.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r video_to_picture_widget.app
	-$(DEL_FILE) Makefile


####### Sub-libraries

xcodeproj:
	@$(QMAKE) -spec macx-xcode "$(EXPORT__PRO_FILE_)" -spec macx-clang CONFIG+=qtquickcompiler

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc_mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp
moc_mainwindow.cpp: ../video_to_picture_widget/mainwindow.h \
		../../../Qt/6.5.1/macos/lib/QtWidgets.framework/Headers/QMainWindow \
		../../../Qt/6.5.1/macos/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../../Qt/6.5.1/macos/libexec/moc
	/Users/twinklecat/Qt/6.5.1/macos/libexec/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -D__cplusplus=199711L -D__APPLE_CC__=6000 -D__clang__ -D__clang_major__=14 -D__clang_minor__=0 -D__clang_patchlevel__=3 -D__GNUC__=4 -D__GNUC_MINOR__=2 -D__GNUC_PATCHLEVEL__=1 -I/Users/twinklecat/Qt/6.5.1/macos/mkspecs/macx-clang -I/Users/twinklecat/Downloads/video_to_picture_widget/video_to_picture_widget -I/opt/homebrew/Cellar/opencv/4.7.0_2/include/opencv4 -I/Users/twinklecat/Qt/6.5.1/macos/lib/QtWidgets.framework/Headers -I/Users/twinklecat/Qt/6.5.1/macos/lib/QtGui.framework/Headers -I/Users/twinklecat/Qt/6.5.1/macos/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/14.0.3/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -F/Users/twinklecat/Qt/6.5.1/macos/lib ../video_to_picture_widget/mainwindow.h -o moc_mainwindow.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: ../video_to_picture_widget/mainwindow.ui \
		../../../Qt/6.5.1/macos/libexec/uic
	/Users/twinklecat/Qt/6.5.1/macos/libexec/uic ../video_to_picture_widget/mainwindow.ui -o ui_mainwindow.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: ../video_to_picture_widget/main.cpp /opt/homebrew/Cellar/opencv/4.7.0_2/include/opencv4/opencv2/opencv.hpp \
		/opt/homebrew/Cellar/opencv/4.7.0_2/include/opencv4/opencv2/opencv_modules.hpp \
		/opt/homebrew/Cellar/opencv/4.7.0_2/include/opencv4/opencv2/core.hpp \
		/opt/homebrew/Cellar/opencv/4.7.0_2/include/opencv4/opencv2/core/cvdef.h \
		/opt/homebrew/Cellar/opencv/4.7.0_2/include/opencv4/opencv2/core/version.hpp \
		/opt/homebrew/Cellar/opencv/4.7.0_2/include/opencv4/opencv2/core/hal/interface.h \
		/opt/homebrew/Cellar/opencv/4.7.0_2/include/opencv4/opencv2/core/cv_cpu_dispatch.h \
		/opt/homebrew/Cellar/opencv/4.7.0_2/include/opencv4/opencv2/core/cv_cpu_helper.h \
		/opt/homebrew/Cellar/opencv/4.7.0_2/include/opencv4/opencv2/core/hal/msa_macros.h \
		/opt/homebrew/Cellar/opencv/4.7.0_2/include/opencv4/opencv2/core/fast_math.hpp \
		/opt/homebrew/Cellar/opencv/4.7.0_2/include/opencv4/opencv2/core/base.hpp \
		/opt/homebrew/Cellar/opencv/4.7.0_2/include/opencv4/opencv2/core/cvstd.hpp \
		/opt/homebrew/Cellar/opencv/4.7.0_2/include/opencv4/opencv2/core/cvstd_wrapper.hpp \
		/opt/homebrew/Cellar/opencv/4.7.0_2/include/opencv4/opencv2/core/neon_utils.hpp \
		/opt/homebrew/Cellar/opencv/4.7.0_2/include/opencv4/opencv2/core/vsx_utils.hpp \
		/opt/homebrew/Cellar/opencv/4.7.0_2/include/opencv4/opencv2/core/check.hpp \
		/opt/homebrew/Cellar/opencv/4.7.0_2/include/opencv4/opencv2/core/traits.hpp \
		/opt/homebrew/Cellar/opencv/4.7.0_2/include/opencv4/opencv2/core/matx.hpp \
		/opt/homebrew/Cellar/opencv/4.7.0_2/include/opencv4/opencv2/core/saturate.hpp \
		/opt/homebrew/Cellar/opencv/4.7.0_2/include/opencv4/opencv2/core/types.hpp \
		/opt/homebrew/Cellar/opencv/4.7.0_2/include/opencv4/opencv2/core/mat.hpp \
		/opt/homebrew/Cellar/opencv/4.7.0_2/include/opencv4/opencv2/core/bufferpool.hpp \
		/opt/homebrew/Cellar/opencv/4.7.0_2/include/opencv4/opencv2/core/mat.inl.hpp \
		/opt/homebrew/Cellar/opencv/4.7.0_2/include/opencv4/opencv2/core/persistence.hpp \
		/opt/homebrew/Cellar/opencv/4.7.0_2/include/opencv4/opencv2/core/operations.hpp \
		/opt/homebrew/Cellar/opencv/4.7.0_2/include/opencv4/opencv2/core/cvstd.inl.hpp \
		/opt/homebrew/Cellar/opencv/4.7.0_2/include/opencv4/opencv2/core/utility.hpp \
		/opt/homebrew/Cellar/opencv/4.7.0_2/include/opencv4/opencv2/core/utils/instrumentation.hpp \
		/opt/homebrew/Cellar/opencv/4.7.0_2/include/opencv4/opencv2/core/utils/tls.hpp \
		/opt/homebrew/Cellar/opencv/4.7.0_2/include/opencv4/opencv2/core/optim.hpp \
		/opt/homebrew/Cellar/opencv/4.7.0_2/include/opencv4/opencv2/core/ovx.hpp \
		/opt/homebrew/Cellar/opencv/4.7.0_2/include/opencv4/opencv2/calib3d.hpp \
		/opt/homebrew/Cellar/opencv/4.7.0_2/include/opencv4/opencv2/features2d.hpp \
		/opt/homebrew/Cellar/opencv/4.7.0_2/include/opencv4/opencv2/flann/miniflann.hpp \
		/opt/homebrew/Cellar/opencv/4.7.0_2/include/opencv4/opencv2/flann/defines.h \
		/opt/homebrew/Cellar/opencv/4.7.0_2/include/opencv4/opencv2/flann/config.h \
		/opt/homebrew/Cellar/opencv/4.7.0_2/include/opencv4/opencv2/core/affine.hpp \
		/opt/homebrew/Cellar/opencv/4.7.0_2/include/opencv4/opencv2/dnn.hpp \
		/opt/homebrew/Cellar/opencv/4.7.0_2/include/opencv4/opencv2/dnn/dnn.hpp \
		/opt/homebrew/Cellar/opencv/4.7.0_2/include/opencv4/opencv2/core/async.hpp \
		/opt/homebrew/Cellar/opencv/4.7.0_2/include/opencv4/opencv2/dnn/version.hpp \
		/opt/homebrew/Cellar/opencv/4.7.0_2/include/opencv4/opencv2/dnn/dict.hpp \
		/opt/homebrew/Cellar/opencv/4.7.0_2/include/opencv4/opencv2/dnn/layer.hpp \
		/opt/homebrew/Cellar/opencv/4.7.0_2/include/opencv4/opencv2/dnn/dnn.inl.hpp \
		/opt/homebrew/Cellar/opencv/4.7.0_2/include/opencv4/opencv2/dnn/utils/inference_engine.hpp \
		/opt/homebrew/Cellar/opencv/4.7.0_2/include/opencv4/opencv2/flann.hpp \
		/opt/homebrew/Cellar/opencv/4.7.0_2/include/opencv4/opencv2/flann/flann_base.hpp \
		/opt/homebrew/Cellar/opencv/4.7.0_2/include/opencv4/opencv2/flann/general.h \
		/opt/homebrew/Cellar/opencv/4.7.0_2/include/opencv4/opencv2/flann/matrix.h \
		/opt/homebrew/Cellar/opencv/4.7.0_2/include/opencv4/opencv2/flann/params.h \
		/opt/homebrew/Cellar/opencv/4.7.0_2/include/opencv4/opencv2/flann/any.h \
		/opt/homebrew/Cellar/opencv/4.7.0_2/include/opencv4/opencv2/flann/saving.h \
		/opt/homebrew/Cellar/opencv/4.7.0_2/include/opencv4/opencv2/flann/nn_index.h \
		/opt/homebrew/Cellar/opencv/4.7.0_2/include/opencv4/opencv2/flann/result_set.h \
		/opt/homebrew/Cellar/opencv/4.7.0_2/include/opencv4/opencv2/flann/all_indices.h \
		/opt/homebrew/Cellar/opencv/4.7.0_2/include/opencv4/opencv2/flann/kdtree_index.h \
		/opt/homebrew/Cellar/opencv/4.7.0_2/include/opencv4/opencv2/flann/dynamic_bitset.h \
		/opt/homebrew/Cellar/opencv/4.7.0_2/include/opencv4/opencv2/flann/dist.h \
		/opt/homebrew/Cellar/opencv/4.7.0_2/include/opencv4/opencv2/flann/heap.h \
		/opt/homebrew/Cellar/opencv/4.7.0_2/include/opencv4/opencv2/flann/allocator.h \
		/opt/homebrew/Cellar/opencv/4.7.0_2/include/opencv4/opencv2/flann/random.h \
		/opt/homebrew/Cellar/opencv/4.7.0_2/include/opencv4/opencv2/flann/kdtree_single_index.h \
		/opt/homebrew/Cellar/opencv/4.7.0_2/include/opencv4/opencv2/flann/kmeans_index.h \
		/opt/homebrew/Cellar/opencv/4.7.0_2/include/opencv4/opencv2/flann/logger.h \
		/opt/homebrew/Cellar/opencv/4.7.0_2/include/opencv4/opencv2/flann/composite_index.h \
		/opt/homebrew/Cellar/opencv/4.7.0_2/include/opencv4/opencv2/flann/linear_index.h \
		/opt/homebrew/Cellar/opencv/4.7.0_2/include/opencv4/opencv2/flann/hierarchical_clustering_index.h \
		/opt/homebrew/Cellar/opencv/4.7.0_2/include/opencv4/opencv2/flann/lsh_index.h \
		/opt/homebrew/Cellar/opencv/4.7.0_2/include/opencv4/opencv2/flann/lsh_table.h \
		/opt/homebrew/Cellar/opencv/4.7.0_2/include/opencv4/opencv2/flann/autotuned_index.h \
		/opt/homebrew/Cellar/opencv/4.7.0_2/include/opencv4/opencv2/flann/ground_truth.h \
		/opt/homebrew/Cellar/opencv/4.7.0_2/include/opencv4/opencv2/flann/index_testing.h \
		/opt/homebrew/Cellar/opencv/4.7.0_2/include/opencv4/opencv2/flann/timer.h \
		/opt/homebrew/Cellar/opencv/4.7.0_2/include/opencv4/opencv2/flann/sampling.h \
		/opt/homebrew/Cellar/opencv/4.7.0_2/include/opencv4/opencv2/highgui.hpp \
		/opt/homebrew/Cellar/opencv/4.7.0_2/include/opencv4/opencv2/imgcodecs.hpp \
		/opt/homebrew/Cellar/opencv/4.7.0_2/include/opencv4/opencv2/videoio.hpp \
		/opt/homebrew/Cellar/opencv/4.7.0_2/include/opencv4/opencv2/imgproc.hpp \
		/opt/homebrew/Cellar/opencv/4.7.0_2/include/opencv4/opencv2/imgproc/segmentation.hpp \
		/opt/homebrew/Cellar/opencv/4.7.0_2/include/opencv4/opencv2/ml.hpp \
		/opt/homebrew/Cellar/opencv/4.7.0_2/include/opencv4/opencv2/ml/ml.inl.hpp \
		/opt/homebrew/Cellar/opencv/4.7.0_2/include/opencv4/opencv2/objdetect.hpp \
		/opt/homebrew/Cellar/opencv/4.7.0_2/include/opencv4/opencv2/objdetect/detection_based_tracker.hpp \
		/opt/homebrew/Cellar/opencv/4.7.0_2/include/opencv4/opencv2/objdetect/face.hpp \
		/opt/homebrew/Cellar/opencv/4.7.0_2/include/opencv4/opencv2/objdetect/aruco_detector.hpp \
		/opt/homebrew/Cellar/opencv/4.7.0_2/include/opencv4/opencv2/objdetect/aruco_dictionary.hpp \
		/opt/homebrew/Cellar/opencv/4.7.0_2/include/opencv4/opencv2/objdetect/aruco_board.hpp \
		/opt/homebrew/Cellar/opencv/4.7.0_2/include/opencv4/opencv2/objdetect/charuco_detector.hpp \
		/opt/homebrew/Cellar/opencv/4.7.0_2/include/opencv4/opencv2/photo.hpp \
		/opt/homebrew/Cellar/opencv/4.7.0_2/include/opencv4/opencv2/stitching.hpp \
		/opt/homebrew/Cellar/opencv/4.7.0_2/include/opencv4/opencv2/stitching/warpers.hpp \
		/opt/homebrew/Cellar/opencv/4.7.0_2/include/opencv4/opencv2/stitching/detail/warpers.hpp \
		/opt/homebrew/Cellar/opencv/4.7.0_2/include/opencv4/opencv2/core/cuda.hpp \
		/opt/homebrew/Cellar/opencv/4.7.0_2/include/opencv4/opencv2/core/cuda_types.hpp \
		/opt/homebrew/Cellar/opencv/4.7.0_2/include/opencv4/opencv2/core/cuda.inl.hpp \
		/opt/homebrew/Cellar/opencv/4.7.0_2/include/opencv4/opencv2/stitching/detail/warpers_inl.hpp \
		/opt/homebrew/Cellar/opencv/4.7.0_2/include/opencv4/opencv2/stitching/detail/matchers.hpp \
		/opt/homebrew/Cellar/opencv/4.7.0_2/include/opencv4/opencv2/stitching/detail/motion_estimators.hpp \
		/opt/homebrew/Cellar/opencv/4.7.0_2/include/opencv4/opencv2/stitching/detail/util.hpp \
		/opt/homebrew/Cellar/opencv/4.7.0_2/include/opencv4/opencv2/stitching/detail/util_inl.hpp \
		/opt/homebrew/Cellar/opencv/4.7.0_2/include/opencv4/opencv2/stitching/detail/camera.hpp \
		/opt/homebrew/Cellar/opencv/4.7.0_2/include/opencv4/opencv2/stitching/detail/exposure_compensate.hpp \
		/opt/homebrew/Cellar/opencv/4.7.0_2/include/opencv4/opencv2/stitching/detail/seam_finders.hpp \
		/opt/homebrew/Cellar/opencv/4.7.0_2/include/opencv4/opencv2/stitching/detail/blenders.hpp \
		/opt/homebrew/Cellar/opencv/4.7.0_2/include/opencv4/opencv2/video.hpp \
		/opt/homebrew/Cellar/opencv/4.7.0_2/include/opencv4/opencv2/video/tracking.hpp \
		/opt/homebrew/Cellar/opencv/4.7.0_2/include/opencv4/opencv2/video/background_segm.hpp \
		../../../Qt/6.5.1/macos/lib/QtWidgets.framework/Headers/QApplication \
		../../../Qt/6.5.1/macos/lib/QtWidgets.framework/Headers/qapplication.h \
		../../../Qt/6.5.1/macos/lib/QtWidgets.framework/Headers/QWidget \
		../../../Qt/6.5.1/macos/lib/QtWidgets.framework/Headers/qwidget.h \
		../../../Qt/6.5.1/macos/lib/QtWidgets.framework/Headers/QBoxLayout \
		../../../Qt/6.5.1/macos/lib/QtWidgets.framework/Headers/qboxlayout.h \
		../../../Qt/6.5.1/macos/lib/QtWidgets.framework/Headers/QLabel \
		../../../Qt/6.5.1/macos/lib/QtWidgets.framework/Headers/qlabel.h \
		../../../Qt/6.5.1/macos/lib/QtGui.framework/Headers/QDropEvent \
		../../../Qt/6.5.1/macos/lib/QtGui.framework/Headers/qevent.h \
		../../../Qt/6.5.1/macos/lib/QtCore.framework/Headers/QUrl \
		../../../Qt/6.5.1/macos/lib/QtCore.framework/Headers/qurl.h \
		../../../Qt/6.5.1/macos/lib/QtCore.framework/Headers/QMimeData \
		../../../Qt/6.5.1/macos/lib/QtCore.framework/Headers/qmimedata.h \
		../../../Qt/6.5.1/macos/lib/QtWidgets.framework/Headers/QFileDialog \
		../../../Qt/6.5.1/macos/lib/QtWidgets.framework/Headers/qfiledialog.h \
		../../../Qt/6.5.1/macos/lib/QtWidgets.framework/Headers/QMessageBox \
		../../../Qt/6.5.1/macos/lib/QtWidgets.framework/Headers/qmessagebox.h \
		../../../Qt/6.5.1/macos/lib/QtWidgets.framework/Headers/QPushButton \
		../../../Qt/6.5.1/macos/lib/QtWidgets.framework/Headers/qpushbutton.h \
		../../../Qt/6.5.1/macos/lib/QtWidgets.framework/Headers/QProgressBar \
		../../../Qt/6.5.1/macos/lib/QtWidgets.framework/Headers/qprogressbar.h \
		../../../Qt/6.5.1/macos/lib/QtWidgets.framework/Headers/QProgressDialog \
		../../../Qt/6.5.1/macos/lib/QtWidgets.framework/Headers/qprogressdialog.h \
		../../../Qt/6.5.1/macos/lib/QtWidgets.framework/Headers/QLineEdit \
		../../../Qt/6.5.1/macos/lib/QtWidgets.framework/Headers/qlineedit.h \
		../../../Qt/6.5.1/macos/lib/QtGui.framework/Headers/QDoubleValidator \
		../../../Qt/6.5.1/macos/lib/QtGui.framework/Headers/qvalidator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o ../video_to_picture_widget/main.cpp

mainwindow.o: ../video_to_picture_widget/mainwindow.cpp ../video_to_picture_widget/mainwindow.h \
		../../../Qt/6.5.1/macos/lib/QtWidgets.framework/Headers/QMainWindow \
		../../../Qt/6.5.1/macos/lib/QtWidgets.framework/Headers/qmainwindow.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o ../video_to_picture_widget/mainwindow.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/video_to_picture_widget/bin || mkdir -p $(INSTALL_ROOT)/opt/video_to_picture_widget/bin
	$(DEL_FILE) -r $(INSTALL_ROOT)/opt/video_to_picture_widget/bin/video_to_picture_widget.app
	
	$(QINSTALL) video_to_picture_widget.app $(INSTALL_ROOT)/opt/video_to_picture_widget/bin/video_to_picture_widget.app
	-$(STRIP) $(INSTALL_ROOT)/opt/video_to_picture_widget/bin/video_to_picture_widget.app/Contents/MacOS/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/opt/video_to_picture_widget/bin/video_to_picture_widget.app
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/video_to_picture_widget/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

.SUFFIXES:

